[versions]
agp = "8.9.1"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.28"
kotlinx-serialization = "1.7.3" # https://github.com/Kotlin/kotlinx.serialization/releases
kotlinx-coroutines = "1.8.1" # https://github.com/Kotlin/kotlinx.coroutines/releases
room = "2.6.0"
kotest = "5.5.2"
lifecycle = "2.8.5"
junit-jupiter = "5.8.1"

[libraries]
androidx-core-ktx = "androidx.core:core-ktx:1.9.0"
okhttp = "com.squareup.okhttp3:okhttp:4.12.0"
kotlin-coroutines-okhttp = "ru.gildor.coroutines:kotlin-coroutines-okhttp:1.0"
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-collections = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-startup = "androidx.startup:startup-runtime:1.2.0"
android-desugaring = "com.android.tools:desugar_jdk_libs:2.0.4"
lifecycle-process = {module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle"}
mockk = "io.mockk:mockk:1.13.2"
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
